[package]
name = "neuronal_network_rust"
version = "0.1.0"
authors = ["cote celeste <celeste@cote21.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.18"
rand = "0.7.3"
rand_distr = "0.2.2"
